/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register new user and create tenant (first user becomes admin).
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user and set auth cookies.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate refresh token and issue new token pair.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear auth cookies.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current user profile with all workspace memberships.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/switch-workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Switch Workspace
         * @description Switch the active workspace for the authenticated user.
         */
        post: operations["switch_workspace_api_v1_auth_switch_workspace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/create-workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workspace
         * @description Create a new workspace for the authenticated user.
         */
        post: operations["create_workspace_api_v1_auth_create_workspace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Invite
         * @description Create an invite code for a specific email address (admin only).
         *
         *     The code is 8-char alphanumeric, expires after the configured hours,
         *     and is bound to the invited email — only that email may redeem it.
         */
        post: operations["create_invite_api_v1_auth_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invite/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem Invite New User
         * @description Redeem an invite code to register a new account and join a workspace.
         *
         *     The requesting email MUST match the email the invite was issued to.
         *     For already-registered users, use POST /invite/join instead.
         */
        post: operations["redeem_invite_new_user_api_v1_auth_invite_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invite/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Workspace
         * @description Redeem an invite code for an already-authenticated user to join an additional workspace.
         *
         *     The authenticated user's email MUST match the email the invite was issued to.
         */
        post: operations["join_workspace_api_v1_auth_invite_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invites
         * @description List pending invites for the active workspace (admin only).
         */
        get: operations["list_invites_api_v1_auth_invites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invites/{token_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Invite
         * @description Revoke pending invite by token_hash prefix (admin only).
         */
        delete: operations["revoke_invite_api_v1_auth_invites__token_hash__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tenant Whoami
         * @description Get current tenant info from authenticated user.
         */
        get: operations["tenant_whoami_api_v1_tenants_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Registry */
        get: operations["list_registry_api_v1_providers_get"];
        put?: never;
        /** Register Provider Gateway */
        post: operations["register_provider_gateway_api_v1_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/manual-cost-line": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Manual Gateway */
        post: operations["record_manual_gateway_api_v1_providers_manual_cost_line_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Provider */
        get: operations["inspect_provider_api_v1_providers__provider_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Budgets */
        patch: operations["patch_budgets_api_v1_providers__provider_id__budgets_patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/polling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Polling */
        patch: operations["patch_polling_api_v1_providers__provider_id__polling_patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Credentials
         * @description Update provider API key and/or webhook secret.
         */
        patch: operations["patch_credentials_api_v1_providers__provider_id__credentials_patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/poll-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Polling Connection
         * @description Test provider polling credentials without fetching costs.
         */
        post: operations["test_polling_connection_api_v1_providers__provider_id__poll_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Tags */
        patch: operations["patch_tags_api_v1_providers__provider_id__tags_patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/backfill-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backfill Tags */
        post: operations["backfill_tags_api_v1_providers__provider_id__backfill_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/health-probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule Health Pulse */
        post: operations["schedule_health_pulse_api_v1_providers__provider_id__health_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invoice Router */
        get: operations["list_invoice_router_api_v1_providers__provider_id__invoices_get"];
        put?: never;
        /** Register Invoice Router */
        post: operations["register_invoice_router_api_v1_providers__provider_id__invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Overview Router */
        get: operations["monthly_overview_router_api_v1_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/charts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charts Router */
        get: operations["charts_router_api_v1_analytics_charts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/cost-allocation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost Allocation Router */
        get: operations["cost_allocation_router_api_v1_analytics_cost_allocation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/stripe/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stripe-signed webhook tunnel */
        post: operations["stripe_tunnel_api_v1_webhooks_stripe__provider_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/generic/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generic HMAC webhook tunnel */
        post: operations["generic_tunnel_api_v1_webhooks_generic__provider_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/rollup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Rollup */
        post: operations["manual_rollup_api_v1_ops_rollup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/alerts-scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Alert Pulse */
        post: operations["manual_alert_pulse_api_v1_ops_alerts_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/global-rollups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Global Rollup */
        post: operations["trigger_global_rollup_api_v1_ops_global_rollups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ops/refresh-fx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Fx Refresh */
        post: operations["trigger_fx_refresh_api_v1_ops_refresh_fx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness Ping */
        get: operations["liveness_ping_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness Ping */
        get: operations["readiness_ping_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddToWorkspaceRequest
         * @description Used when an already-registered user redeems an invite (no new account created).
         */
        AddToWorkspaceRequest: {
            /** Invite Code */
            invite_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** AllocationRow */
        AllocationRow: {
            /** Tag Key */
            tag_key: string;
            /** Tag Value */
            tag_value: string;
            /**
             * Provider Breakdown
             * @description provider_id → total_base for this tag combination
             */
            provider_breakdown: {
                [key: string]: string;
            };
            /** Total Base */
            total_base: string;
        };
        /** BackfillTagsResult */
        BackfillTagsResult: {
            /** Provider Id */
            provider_id: string;
            /** Events Updated */
            events_updated: number;
        };
        /**
         * BillingType
         * @enum {string}
         */
        BillingType: "prepaid" | "postpaid";
        /** ChartBundle */
        ChartBundle: {
            /** Pie Slices */
            pie_slices: components["schemas"]["PieSlice"][];
            /** Mtd Timeline Points */
            mtd_timeline_points: components["schemas"]["TimelinePoint"][];
            /** Tag Pie Slices */
            tag_pie_slices?: components["schemas"]["TagPieSlice"][];
        };
        /** ChartsResponse */
        ChartsResponse: {
            charts: components["schemas"]["ChartBundle"];
            dashed_projection_point: components["schemas"]["PredictionPayload"];
        };
        /** CostAllocationReport */
        CostAllocationReport: {
            /** Tenant Id */
            tenant_id: string;
            /** Month Key */
            month_key: string;
            /** Base Currency */
            base_currency: string;
            /** Rows */
            rows: components["schemas"]["AllocationRow"][];
            /** Grand Total Base */
            grand_total_base: string;
        };
        /** CostEventEcho */
        CostEventEcho: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Amount Original */
            amount_original: string;
            /** Currency Original */
            currency_original: string;
            /** Amount Base */
            amount_base: string;
            /** Fx Rate Source */
            fx_rate_source: string | null;
            /** Tags */
            tags?: {
                [key: string]: string;
            };
        };
        /** CreateInviteRequest */
        CreateInviteRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Role
             * @default viewer
             * @enum {string}
             */
            role: "editor" | "viewer";
        };
        /** CreateInviteResponse */
        CreateInviteResponse: {
            /** Invite Code */
            invite_code: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /** Tenant Name */
            tenant_name: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthStatus
         * @enum {string}
         */
        HealthStatus: "up" | "down" | "degraded" | "unknown";
        /** HealthTelemetryOut */
        HealthTelemetryOut: {
            /** Tenant Id */
            tenant_id: string;
            /** Provider Id */
            provider_id: string;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
            status: components["schemas"]["HealthStatus"];
            /** Http Status */
            http_status: number | null;
            /** Latency Ms */
            latency_ms: number | null;
            /** Error Detail */
            error_detail: string | null;
        };
        /** InviteInfo */
        InviteInfo: {
            /** Token Hash */
            token_hash: string;
            /** Short Code */
            short_code: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Invited By */
            invited_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Used At */
            used_at?: string | null;
            /** Used By */
            used_by?: string | null;
        };
        /** InvoiceCreate */
        InvoiceCreate: {
            /** Amount Original */
            amount_original: number | string;
            /**
             * Currency Original
             * @description ISO-4217 code
             */
            currency_original: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Stored Object Key */
            stored_object_key?: string | null;
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Provider Id */
            provider_id: string;
            /** Amount Original */
            amount_original: string;
            /** Currency Original */
            currency_original: string;
            /** Amount Base */
            amount_base: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Notes */
            notes: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ManualCostPayload */
        ManualCostPayload: {
            /** Provider Id */
            provider_id: string;
            /** Amount Original */
            amount_original: number | string;
            /** Currency Original */
            currency_original: string;
            /**
             * Occurred At
             * @description Defaults to ingestion clock when omitted.
             */
            occurred_at?: string | null;
            /**
             * Tags
             * @description Optional event-level tags (merged with provider defaults; event wins on conflict)
             */
            tags?: {
                [key: string]: string;
            } | null;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Roles */
            roles: string[];
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Workspaces */
            workspaces?: components["schemas"]["WorkspaceSummary"][];
        };
        /** MonthlyOverview */
        MonthlyOverview: {
            /** Tenant Id */
            tenant_id: string;
            /** Month Key */
            month_key: string;
            /** Current Month Total Base */
            current_month_total_base: string;
            /** Previous Month Total Base */
            previous_month_total_base: string;
            /**
             * Growth Pct
             * @description Fractional delta vs prev month totals
             */
            growth_pct: string;
            /** Base Currency */
            base_currency: string;
            /** Breakdown By Provider Base */
            breakdown_by_provider_base: {
                [key: string]: string;
            };
            /**
             * Breakdown By Tag
             * @description Nested breakdown: {tag_key: {tag_value: total_base}}
             */
            breakdown_by_tag?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** PendingInvitesResponse */
        PendingInvitesResponse: {
            /** Invites */
            invites: components["schemas"]["InviteInfo"][];
        };
        /** PieSlice */
        PieSlice: {
            /** Provider Id */
            provider_id: string;
            /** Spent Base */
            spent_base: string;
        };
        /** PredictionPayload */
        PredictionPayload: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "postpaid" | "prepaid" | "unset";
            /** Predicted End Of Month Total */
            predicted_end_of_month_total?: string | null;
            /** Projected Days Remaining */
            projected_days_remaining?: string | null;
            /** Model Note */
            model_note?: string | null;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Display Name */
            display_name: string;
            provider_kind: components["schemas"]["ProviderKind"];
            billing_type: components["schemas"]["BillingType"];
            /**
             * Access Key
             * @description Captured once ; encrypted immediately before persistence
             */
            access_key: string;
            /** Monthly Budget Limit Base */
            monthly_budget_limit_base?: number | string | null;
            /** Prepaid Balance Base */
            prepaid_balance_base?: number | string | null;
            /** Base Url Health */
            base_url_health?: string | null;
            /** Webhook Secret */
            webhook_secret?: string | null;
            /** Credential Key Id */
            credential_key_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Default Tags
             * @description Default cost-allocation tags inherited by events
             */
            default_tags?: {
                [key: string]: string;
            } | null;
            /**
             * Is Polling Enabled
             * @description Enable automatic usage polling
             * @default true
             */
            is_polling_enabled: boolean;
            /**
             * Polling Interval Seconds
             * @description Override global polling interval
             */
            polling_interval_seconds?: number | null;
        };
        /**
         * ProviderKind
         * @enum {string}
         */
        ProviderKind: "openai" | "cursor" | "aws" | "stripe" | "generic";
        /** ProviderOut */
        ProviderOut: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Display Name */
            display_name: string;
            /** Provider Kind */
            provider_kind: string;
            /** Billing Type */
            billing_type: string;
            /** Monthly Budget Limit Base */
            monthly_budget_limit_base: string | null;
            /** Prepaid Balance Base */
            prepaid_balance_base: string | null;
            /** Base Url Health */
            base_url_health: string | null;
            /** Credential Key Id */
            credential_key_id: string | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Default Tags */
            default_tags: {
                [key: string]: string;
            };
            /** Has Access Key */
            has_access_key: boolean;
            /** Access Key Masked */
            access_key_masked: string | null;
            /** Webhook Secret Masked */
            webhook_secret_masked: string | null;
            /** Is Polling Enabled */
            is_polling_enabled: boolean;
            /** Polling Interval Seconds */
            polling_interval_seconds: number | null;
            /**
             * Polling Status
             * @description Current polling state from cursor
             */
            polling_status?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProviderPollTestResult */
        ProviderPollTestResult: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /** ProviderUpdateBudgets */
        ProviderUpdateBudgets: {
            /** Monthly Budget Limit Base */
            monthly_budget_limit_base?: number | string | null;
            /** Prepaid Balance Base */
            prepaid_balance_base?: number | string | null;
        };
        /** ProviderUpdateCredentials */
        ProviderUpdateCredentials: {
            /**
             * Access Key
             * @description New API key (leave empty to keep current)
             */
            access_key?: string | null;
            /**
             * Webhook Secret
             * @description New webhook secret (leave empty to keep current)
             */
            webhook_secret?: string | null;
        };
        /** ProviderUpdatePolling */
        ProviderUpdatePolling: {
            /** Is Polling Enabled */
            is_polling_enabled?: boolean | null;
            /** Polling Interval Seconds */
            polling_interval_seconds?: number | null;
        };
        /** ProviderUpdateTags */
        ProviderUpdateTags: {
            /**
             * Default Tags
             * @description New default cost-allocation tags for this provider
             */
            default_tags: {
                [key: string]: string;
            };
        };
        /** RedeemInviteRequest */
        RedeemInviteRequest: {
            /** Invite Code */
            invite_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
            /** Tenant Name */
            tenant_name: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Base Currency
             * @default USD
             */
            base_currency: string;
        };
        /** SwitchWorkspaceRequest */
        SwitchWorkspaceRequest: {
            /** Tenant Id */
            tenant_id: string;
        };
        /** TagPieSlice */
        TagPieSlice: {
            /** Tag Key */
            tag_key: string;
            /** Tag Value */
            tag_value: string;
            /** Spent Base */
            spent_base: string;
        };
        /** TenantOut */
        TenantOut: {
            /** Tenant Id */
            tenant_id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Base Currency */
            base_currency: string;
        };
        /** TimelinePoint */
        TimelinePoint: {
            /**
             * Iso Day Label
             * Format: date
             */
            iso_day_label: string;
            /** Cumulative Spent Base */
            cumulative_spent_base: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceSummary */
        WorkspaceSummary: {
            /** Tenant Id */
            tenant_id: string;
            /** Tenant Name */
            tenant_name: string;
            /** Roles */
            roles: string[];
            /** Is Active */
            is_active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    switch_workspace_api_v1_auth_switch_workspace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workspace_api_v1_auth_create_workspace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_api_v1_auth_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_invite_new_user_api_v1_auth_invite_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_workspace_api_v1_auth_invite_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddToWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invites_api_v1_auth_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingInvitesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_api_v1_auth_invites__token_hash__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token_hash: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_whoami_api_v1_tenants_whoami_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_registry_api_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_provider_gateway_api_v1_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_manual_gateway_api_v1_providers_manual_cost_line_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualCostPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostEventEcho"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_provider_api_v1_providers__provider_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_budgets_api_v1_providers__provider_id__budgets_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdateBudgets"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_polling_api_v1_providers__provider_id__polling_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdatePolling"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_credentials_api_v1_providers__provider_id__credentials_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdateCredentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_polling_connection_api_v1_providers__provider_id__poll_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPollTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tags_api_v1_providers__provider_id__tags_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdateTags"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backfill_tags_api_v1_providers__provider_id__backfill_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackfillTagsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_health_pulse_api_v1_providers__provider_id__health_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthTelemetryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoice_router_api_v1_providers__provider_id__invoices_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_invoice_router_api_v1_providers__provider_id__invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_overview_router_api_v1_analytics_overview_get: {
        parameters: {
            query?: {
                /** @description yyyy-mm anchored to Tenant.timezone when omitted. */
                month?: string | null;
                /** @description Filter by tag key (requires tag_value) */
                tag_key?: string | null;
                /** @description Filter by tag value (requires tag_key) */
                tag_value?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charts_router_api_v1_analytics_charts_get: {
        parameters: {
            query?: {
                month?: string | null;
                /** @description Filter by tag key (requires tag_value) */
                tag_key?: string | null;
                /** @description Filter by tag value (requires tag_key) */
                tag_value?: string | null;
                /** @description Tag key to group pie slices by */
                group_by_tag?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_allocation_router_api_v1_analytics_cost_allocation_get: {
        parameters: {
            query: {
                /** @description yyyy-mm */
                month?: string | null;
                /** @description Comma-separated tag keys to break down by, e.g. 'team,env' */
                tag_keys: string;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostAllocationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_tunnel_api_v1_webhooks_stripe__provider_id__post: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        /** @description Raw Stripe **event JSON** (same bytes Stripe POSTs). Header **Stripe-Signature** is required when the provider has a **webhook_secret** (use [Stripe CLI](https://stripe.com/docs/stripe-cli) `stripe listen --forward-to ...` or paste a real signed payload). The example is illustrative only — signature will not verify unless you sign it with your secret. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "id": "evt_demo_openapi_001",
                 *       "type": "invoice.paid",
                 *       "data": {
                 *         "object": {
                 *           "amount_paid": 1000,
                 *           "currency": "usd",
                 *           "status_transitions": {
                 *             "paid_at": 1700000000
                 *           }
                 *         }
                 *       }
                 *     }
                 */
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generic_tunnel_api_v1_webhooks_generic__provider_id__post: {
        parameters: {
            query?: never;
            header?: {
                "X-Acs-Signature"?: string | null;
            };
            path: {
                provider_id: string;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        /** @description Raw JSON body (**exact UTF-8 bytes** are HMAC input). Required keys: **event_id**, **amount_original**, **currency_original**. If the provider has **webhook_secret**, set **X-Acs-Signature** to lowercase hex `HMAC_SHA256(utf8(plaintext_secret), body_bytes)` where body_bytes is either the **raw** POST body or **canonical JSON** (sorted keys, `,`/`:` separators — same as `python scripts/xasc_signature_converter.py --canonical`). **Secret** = plaintext you used at provider registration, **not** the `gAAAA…` Fernet value in MongoDB. If the provider was created **without** webhook_secret, omit **X-Acs-Signature** (dev-only). */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "event_id": "evt_acs_demo_001",
                 *       "amount_original": "10",
                 *       "currency_original": "USD"
                 *     }
                 */
                "application/json": {
                    event_id: string;
                    /** @description Decimal as string (or number); must match ingestion parser */
                    amount_original: string;
                    /** @description ISO 4217, e.g. USD */
                    currency_original: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_rollup_api_v1_ops_rollup_post: {
        parameters: {
            query?: {
                month_key?: string | null;
            };
            header?: {
                "X-Ops-Secret"?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_alert_pulse_api_v1_ops_alerts_scan_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Ops-Secret"?: string | null;
            };
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_global_rollup_api_v1_ops_global_rollups_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Ops-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_fx_refresh_api_v1_ops_refresh_fx_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Ops-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_ping_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_ping_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
